=== api-evangelist/nginx/json-schema/plus-http-api-nginx-ssl-object-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/nginx/refs/heads/main/json-schema/plus-http-api-nginx-ssl-object-schema.json",
  "title": "SSL",
  "description": "NginxSSLObject schema from NGINX Plus REST API",
  "type": "object",
  "properties": {
    "handshakes": {
      "type": "integer",
      "description": "The total number of successful SSL handshakes.",
      "example": 79572
    },
    "handshakes_failed": {
      "type": "integer",
      "description": "The total number of failed SSL handshakes.",
      "example": 21025
    },
    "session_reuses": {
      "type": "integer",
      "description": "The total number of session reuses during SSL handshake.",
      "example": 15762
    },
    "no_common_protocol": {
      "type": "integer",
      "description": "The number of SSL handshakes failed because of no common protocol.",
      "example": 4
    },
    "no_common_cipher": {
      "type": "integer",
      "description": "The number of SSL handshakes failed because of no shared cipher.",
      "example": 2
    },
    "handshake_timeout": {
      "type": "integer",
      "description": "The number of SSL handshakes failed because of a timeout.",
      "example": 0
    },
    "peer_rejected_cert": {
      "type": "integer",
      "description": "The number of failed SSL handshakes when nginx presented the certificate to the client but it was rejected with a corresponding alert message.",
      "example": 0
    },
    "verify_failures": {
      "type": "object",
      "description": "SSL certificate verification errors",
      "properties": {
        "no_cert": {
          "type": "integer",
          "description": "A client did not provide the required certificate.",
          "example": 0
        },
        "expired_cert": {
          "type": "integer",
          "description": "An expired or not yet valid certificate was presented by a client.",
          "example": 2
        },
        "revoked_cert": {
          "type": "integer",
          "description": "A revoked certificate was presented by a client.",
          "example": 1
        },
        "hostname_mismatch": {
          "type": "integer",
          "description": "Server's certificate doesn't match the hostname.",
          "example": 2
        },
        "other": {
          "type": "integer",
          "description": "Other SSL certificate verification errors.",
          "example": 1
        }
      },
      "example": {}
    }
  },
  "example": {
    "handshakes": 79572,
    "handshakes_failed": 21025,
    "session_reuses": 15762,
    "no_common_protocol": 4,
    "no_common_cipher": 2,
    "handshake_timeout": 0,
    "peer_rejected_cert": 0,
    "verify_failures": {
      "no_cert": 0,
      "expired_cert": 2,
      "revoked_cert": 1,
      "hostname_mismatch": 2,
      "other": 1
    }
  }
}

=== api-evangelist/nginx/examples/plus-http-api-nginx-ssl-object-example.json
{
  "handshakes": 79572,
  "handshakes_failed": 21025,
  "session_reuses": 15762,
  "no_common_protocol": 4,
  "no_common_cipher": 2,
  "handshake_timeout": 0,
  "peer_rejected_cert": 0,
  "verify_failures": {
    "no_cert": 0,
    "expired_cert": 2,
    "revoked_cert": 1,
    "hostname_mismatch": 2,
    "other": 1
  }
}
